language: cpp
cache: ccache

dist: bionic
osx_image: xcode11.3

compiler:
- gcc
- clang

os:
- linux
- osx
- windows

arch:
- amd64
- ppc64le
- s390x
- arm64

script:
- cmake -E make_directory Build/
- cmake -E chdir Build/ cmake ..
- cmake -E chdir Build/ cmake --build .