language: cpp
cache: ccache

# Use Linux by default
os: linux
dist: bionic

addons:
  snaps:
  - name: cmake
    confinement: classic
    channel: latest

matrix:
  include:

  - compiler: clang
    cache: false # Fails on precompiled headers otherwise
    before_install: &use-cmake
    - export PATH=/snap/bin/:${PATH}

  - compiler: gcc
    before_install: *use-cmake

  - os: osx
    osx_image: xcode11.3

script:
- cmake -E make_directory Build/
- cmake -E chdir Build/ cmake -DBUILD_TOOLS=YES -DSELF_TEST=YES ..
- cmake -E chdir Build/ cmake --build . --parallel 2
- cmake -E chdir Build/ ctest . --parallel 2
