language: cpp
cache: ccache

matrix:
  include:

  - name: "Leenucks"
    compiler:
    - gcc
    - clang
    dist: bionic
    os: linux

  - name: "Macinsquash"
    os: osx
    osx_image: xcode11.3

  - name: "Windoze"
    os: windows

script:
- cmake -E make_directory Build/
- cmake -E chdir Build/ cmake ..
- cmake -E chdir Build/ cmake --build . --parallel 2
